import {THRESHOLD_LARGE_CODEBASE_FILES} from '@/constants';
import type {ExistingRules} from '@/init/existing-rules-extractor';
import type {ProjectAnalysis} from '@/init/project-analyzer';
import test from 'ava';
import {AgentsTemplateGenerator} from './agents-template-generator';

// Tests for AgentsTemplateGenerator
// Validates AGENTS.md template generation based on project analysis

console.log('\nagents-template-generator.spec.ts');

// Helper to create a minimal ProjectAnalysis object
function createMinimalAnalysis(): ProjectAnalysis {
	return {
		projectPath: '/test/project',
		projectName: 'test-project',
		languages: {
			primary: null,
			secondary: [],
			all: [],
		},
		dependencies: {
			frameworks: [],
			testingFrameworks: [],
			buildTools: [],
			buildInfo: {},
		},
		projectType: 'Unknown',
		keyFiles: {
			config: [],
			documentation: [],
			build: [],
			test: [],
		},
		structure: {
			totalFiles: 100,
			scannedFiles: 100,
			directories: [],
			importantDirectories: [],
		},
		buildCommands: {},
	};
}

test('generateAgentsMd creates basic structure with minimal input', t => {
	const analysis = createMinimalAnalysis();
	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('# AGENTS.md'));
	t.true(result.includes('AI coding agent instructions for **test-project**'));
	t.true(result.includes('## Project Overview'));
	t.true(result.includes('**Project Type:** Unknown'));
	t.true(result.includes('## AI Coding Assistance Notes'));
	t.true(
		result.includes(
			'*This AGENTS.md file was generated by Nanocoder. Update it as your project evolves.*',
		),
	);
});

test('generateAgentsMd includes project description when provided', t => {
	const analysis = createMinimalAnalysis();
	analysis.description = 'A test project for unit testing';

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('A test project for unit testing'));
});

test('generateAgentsMd includes primary language information', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'TypeScript',
		percentage: 85,
		extensions: ['.ts'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('**Primary Language:** TypeScript (85% of codebase)'));
});

test('generateAgentsMd includes secondary languages', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'TypeScript',
		percentage: 70,
		extensions: ['.go'],
		files: [],
	};
	analysis.languages.secondary = [
		{name: 'JavaScript', percentage: 20, extensions: ['.js'], files: []},
		{name: 'CSS', percentage: 10, extensions: ['.css'], files: []},
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(
		result.includes('**Secondary Languages:** JavaScript (20%), CSS (10%)'),
	);
});

test('generateAgentsMd includes framework information', t => {
	const analysis = createMinimalAnalysis();
	analysis.dependencies.frameworks = [
		{name: 'React', version: '18.2.0', category: 'web', confidence: 'high'},
		{name: 'Express.js', category: 'backend', confidence: 'high'},
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('## Architecture'));
	t.true(result.includes('**Key Frameworks & Libraries:**'));
	t.true(result.includes('- React (18.2.0) - web'));
	t.true(result.includes('- Express.js - backend'));
});

test('generateAgentsMd includes important directories', t => {
	const analysis = createMinimalAnalysis();
	analysis.structure.importantDirectories = ['src', 'components', 'utils'];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('**Project Structure:**'));
	t.true(result.includes('- `src/` - Source code'));
	t.true(result.includes('- `components/` - React/UI components'));
	t.true(result.includes('- `utils/` - Utility functions'));
});

test('generateAgentsMd limits directories to 20', t => {
	const analysis = createMinimalAnalysis();
	analysis.structure.importantDirectories = Array.from(
		{length: 30},
		(_, i) => `dir${i}`,
	);

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	// Should only include first 20 directories
	t.true(result.includes('`dir0/`'));
	t.true(result.includes('`dir19/`'));
	t.false(result.includes('`dir20/`'));
});

test('generateAgentsMd includes config files', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.config = [
		'package.json',
		'tsconfig.json',
		'webpack.config.js',
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('## Key Files'));
	t.true(result.includes('**Configuration:**'));
	t.true(result.includes('- `package.json` - Node.js dependencies and scripts'));
	t.true(result.includes('- `tsconfig.json` - TypeScript configuration'));
	t.true(result.includes('- `webpack.config.js` - Webpack build configuration'));
});

test('generateAgentsMd limits config files to 5', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.config = Array.from(
		{length: 10},
		(_, i) => `config${i}.json`,
	);

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	// Should only include first 5 config files
	t.true(result.includes('`config0.json`'));
	t.true(result.includes('`config4.json`'));
	t.false(result.includes('`config5.json`'));
});

test('generateAgentsMd includes documentation files', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.documentation = ['README.md', 'CONTRIBUTING.md'];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('**Documentation:**'));
	t.true(result.includes('- `README.md`'));
	t.true(result.includes('- `CONTRIBUTING.md`'));
});

test('generateAgentsMd limits documentation files to 3', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.documentation = Array.from(
		{length: 5},
		(_, i) => `doc${i}.md`,
	);

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	// Should only include first 3 documentation files
	t.true(result.includes('`doc0.md`'));
	t.true(result.includes('`doc2.md`'));
	t.false(result.includes('`doc3.md`'));
});

test('generateAgentsMd includes build commands', t => {
	const analysis = createMinimalAnalysis();
	analysis.buildCommands = {
		Build: 'npm run build',
		Test: 'npm test',
		Start: 'npm start',
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('## Development Commands'));
	t.true(result.includes('**Build:**'));
	t.true(result.includes('npm run build'));
	t.true(result.includes('**Test:**'));
	t.true(result.includes('npm test'));
	t.true(result.includes('**Start:**'));
	t.true(result.includes('npm start'));
});

test('generateAgentsMd includes TypeScript coding conventions', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'TypeScript',
		percentage: 90,
		extensions: ['.ts'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('## Code Style Guidelines'));
	t.true(result.includes('- Use camelCase for variables and functions'));
	t.true(result.includes('- Use PascalCase for classes and components'));
	t.true(result.includes('- Prefer const/let over var'));
	t.true(result.includes('- Use async/await over callbacks when possible'));
});

test('generateAgentsMd includes React conventions when React is detected', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'JavaScript',
		percentage: 80,
		extensions: ['.js'],
		files: [],
	};
	analysis.dependencies.frameworks = [
		{name: 'React', category: 'web', confidence: 'high'},
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- Use functional components with hooks'));
	t.true(result.includes('- Follow React naming conventions for components'));
});

test('generateAgentsMd includes Python coding conventions', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'Python',
		percentage: 95,
		extensions: ['.py'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('## Code Style Guidelines'));
	t.true(result.includes('- Follow PEP 8 style guide'));
	t.true(result.includes('- Use snake_case for variables and functions'));
	t.true(result.includes('- Use PascalCase for classes'));
	t.true(result.includes('- Include docstrings for functions and classes'));
	t.true(result.includes('- Use type hints where appropriate'));
});

test('generateAgentsMd includes Rust coding conventions', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'Rust',
		percentage: 98,
		extensions: ['.ts'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- Follow Rust naming conventions (snake_case)'));
	t.true(result.includes('- Use cargo fmt for code formatting'));
	t.true(result.includes('- Handle errors explicitly with Result<T, E>'));
	t.true(result.includes('- Prefer owned types over references when possible'));
});

test('generateAgentsMd includes Go coding conventions', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'Go',
		percentage: 92,
		extensions: ['.go'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- Follow Go naming conventions'));
	t.true(result.includes('- Use gofmt for formatting'));
	t.true(result.includes('- Handle errors explicitly'));
	t.true(result.includes('- Use interfaces for abstraction'));
	t.true(result.includes('- Keep functions and methods concise'));
});

test('generateAgentsMd includes Java coding conventions', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'Java',
		percentage: 88,
		extensions: ['.java'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- Follow Java naming conventions'));
	t.true(result.includes('- Use camelCase for methods and variables'));
	t.true(result.includes('- Use PascalCase for classes'));
	t.true(result.includes('- Include JavaDoc for public methods'));
});

test('generateAgentsMd includes testing framework information', t => {
	const analysis = createMinimalAnalysis();
	analysis.dependencies.testingFrameworks = ['Jest', 'React Testing Library'];
	analysis.buildCommands.Test = 'npm test';
	analysis.keyFiles.test = ['app.test.ts', 'utils.test.ts'];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('## Testing'));
	t.true(
		result.includes('**Testing Frameworks:** Jest, React Testing Library'),
	);
	t.true(result.includes('**Run Tests:**'));
	t.true(result.includes('npm test'));
	t.true(result.includes('**Test Files:**'));
	t.true(result.includes('- `app.test.ts`'));
	t.true(result.includes('- `utils.test.ts`'));
});

test('generateAgentsMd limits test files to 5', t => {
	const analysis = createMinimalAnalysis();
	analysis.dependencies.testingFrameworks = ['Jest'];
	analysis.keyFiles.test = Array.from({length: 10}, (_, i) => `test${i}.ts`);

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	// Should only include first 5 test files
	t.true(result.includes('`test0.ts`'));
	t.true(result.includes('`test4.ts`'));
	t.false(result.includes('`test5.ts`'));
});

test('generateAgentsMd includes TypeScript-specific AI notes', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'TypeScript',
		percentage: 85,
		extensions: ['.js'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('## AI Coding Assistance Notes'));
	t.true(
		result.includes(
			'- Check package.json for available scripts before running commands',
		),
	);
	t.true(result.includes('- Be aware of Node.js version requirements'));
	t.true(
		result.includes('- Consider impact on bundle size when adding dependencies'),
	);
});

test('generateAgentsMd includes Python-specific AI notes', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'Python',
		percentage: 90,
		extensions: ['.py'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(
		result.includes('- Check virtual environment setup before running commands'),
	);
	t.true(result.includes('- Be mindful of Python version compatibility'));
	t.true(
		result.includes('- Follow import organization (stdlib, third-party, local)'),
	);
});

test('generateAgentsMd includes Rust-specific AI notes', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'Rust',
		percentage: 95,
		extensions: ['.ts'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(
		result.includes('- Run cargo check before cargo build for faster feedback'),
	);
	t.true(
		result.includes(
			'- Consider memory safety and ownership when suggesting changes',
		),
	);
	t.true(result.includes('- Use cargo clippy for additional linting'));
});

test('generateAgentsMd includes Go-specific AI notes', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'Go',
		percentage: 88,
		extensions: ['.go'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- Run go mod tidy after adding dependencies'));
	t.true(result.includes('- Consider goroutine usage for concurrent operations'));
	t.true(result.includes('- Follow Go idioms for error handling'));
});

test('generateAgentsMd includes default AI notes for unknown language', t => {
	const analysis = createMinimalAnalysis();
	analysis.languages.primary = {
		name: 'Kotlin',
		percentage: 90,
		extensions: ['.js'],
		files: [],
	};

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(
		result.includes('- Check project documentation for specific conventions'),
	);
	t.true(result.includes('- Test changes thoroughly before committing'));
});

test('generateAgentsMd includes React framework notes', t => {
	const analysis = createMinimalAnalysis();
	analysis.dependencies.frameworks = [
		{name: 'React', category: 'web', confidence: 'high'},
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- Follow React hooks best practices'));
	t.true(
		result.includes(
			'- Consider component reusability when creating new components',
		),
	);
});

test('generateAgentsMd includes Next.js framework notes', t => {
	const analysis = createMinimalAnalysis();
	analysis.dependencies.frameworks = [
		{name: 'Next.js', category: 'web', confidence: 'high'},
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(
		result.includes('- Be aware of SSR/SSG implications when making changes'),
	);
	t.true(result.includes('- Check routing structure before adding new pages'));
});

test('generateAgentsMd includes Django framework notes', t => {
	const analysis = createMinimalAnalysis();
	analysis.dependencies.frameworks = [
		{name: 'Django', category: 'backend', confidence: 'high'},
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- Run migrations after model changes'));
	t.true(result.includes('- Follow Django project structure conventions'));
});

test('generateAgentsMd includes Express.js framework notes', t => {
	const analysis = createMinimalAnalysis();
	analysis.dependencies.frameworks = [
		{name: 'Express.js', category: 'backend', confidence: 'high'},
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- Consider middleware order when adding new routes'));
	t.true(result.includes('- Use proper error handling middleware'));
});

test('generateAgentsMd limits framework notes to first 3 frameworks', t => {
	const analysis = createMinimalAnalysis();
	analysis.dependencies.frameworks = [
		{name: 'React', category: 'web', confidence: 'high'},
		{name: 'Next.js', category: 'web', confidence: 'high'},
		{name: 'Express.js', category: 'backend', confidence: 'high'},
		{name: 'Django', category: 'backend', confidence: 'high'}, // This one should be ignored
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- Follow React hooks best practices'));
	t.true(
		result.includes('- Be aware of SSR/SSG implications when making changes'),
	);
	t.true(result.includes('- Consider middleware order when adding new routes'));
	// Django notes should not be included
	t.false(result.includes('- Run migrations after model changes'));
});

test('generateAgentsMd includes file and directory counts', t => {
	const analysis = createMinimalAnalysis();
	analysis.structure.scannedFiles = 250;
	analysis.structure.directories = Array.from({length: 15}, (_, i) => `dir${i}`);

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(
		result.includes(
			'- Project has 250 files across 15 directories',
		),
	);
});

test('generateAgentsMd includes large codebase warning', t => {
	const analysis = createMinimalAnalysis();
	analysis.structure.scannedFiles = THRESHOLD_LARGE_CODEBASE_FILES + 100;

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(
		result.includes('- Large codebase: Focus on specific areas when making changes'),
	);
});

test('generateAgentsMd does not include large codebase warning for small projects', t => {
	const analysis = createMinimalAnalysis();
	analysis.structure.scannedFiles = THRESHOLD_LARGE_CODEBASE_FILES - 1;

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.false(
		result.includes('- Large codebase: Focus on specific areas when making changes'),
	);
});

test('generateAgentsMd includes build configuration warning', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.build = ['webpack.config.js', 'rollup.config.js'];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(
		result.includes(
			'- Check build configuration files before making structural changes',
		),
	);
});

test('generateAgentsMd does not include build warning when no build files', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.build = [];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.false(
		result.includes(
			'- Check build configuration files before making structural changes',
		),
	);
});

test('generateAgentsMd includes repository information', t => {
	const analysis = createMinimalAnalysis();
	analysis.repository = 'https://github.com/test/project';

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('## Repository'));
	t.true(result.includes('**Source:** https://github.com/test/project'));
});

test('generateAgentsMd includes existing rules when provided', t => {
	const analysis = createMinimalAnalysis();
	const existingRules: ExistingRules[] = [
		{
			source: 'CLAUDE.md',
			content: '# Custom Rules\n\nAlways use strict mode.',
			type: 'agents',
		},
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(
		analysis,
		existingRules,
	);

	// The mergeExistingRules function is called, which will include the content
	t.true(result.includes('Always use strict mode'));
});

test('generateAgentsMd handles empty existing rules array', t => {
	const analysis = createMinimalAnalysis();
	const existingRules: ExistingRules[] = [];

	const result = AgentsTemplateGenerator.generateAgentsMd(
		analysis,
		existingRules,
	);

	// Should not fail
	t.true(result.includes('# AGENTS.md'));
});

test('generateAgentsMd provides correct directory descriptions', t => {
	const analysis = createMinimalAnalysis();
	analysis.structure.importantDirectories = [
		'src',
		'source',
		'app',
		'lib',
		'components',
		'pages',
		'api',
		'models',
		'utils',
		'config',
		'docs',
		'tests',
		'unknown_dir',
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- `src/` - Source code'));
	t.true(result.includes('- `source/` - Source code'));
	t.true(result.includes('- `app/` - Application code'));
	t.true(result.includes('- `lib/` - Library code'));
	t.true(result.includes('- `components/` - React/UI components'));
	t.true(result.includes('- `pages/` - Page components'));
	t.true(result.includes('- `api/` - API endpoints'));
	t.true(result.includes('- `models/` - Data models'));
	t.true(result.includes('- `utils/` - Utility functions'));
	t.true(result.includes('- `config/` - Configuration files'));
	t.true(result.includes('- `docs/` - Documentation'));
	t.true(result.includes('- `tests/` - Test files'));
	t.true(result.includes('- `unknown_dir/` - Project files'));
});

test('generateAgentsMd provides correct file descriptions', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.config = [
		'package.json',
		'Cargo.toml',
		'go.mod',
		'requirements.txt',
		'tsconfig.json',
		'webpack.config.js',
		'vite.config.js',
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- `package.json` - Node.js dependencies and scripts'));
	t.true(result.includes('- `Cargo.toml` - Rust package configuration'));
	t.true(result.includes('- `go.mod` - Go module dependencies'));
	t.true(result.includes('- `requirements.txt` - Python dependencies'));
	t.true(result.includes('- `tsconfig.json` - TypeScript configuration'));
});

test('generateAgentsMd handles complex project with all features', t => {
	const analysis = createMinimalAnalysis();
	analysis.projectName = 'ComplexApp';
	analysis.description = 'A complex full-stack application';
	analysis.languages.primary = {
		name: 'TypeScript',
		percentage: 70,
		extensions: ['.ts'],
		files: [],
	};
	analysis.languages.secondary = [
		{name: 'CSS', percentage: 30, extensions: ['.css'], files: []},
	];
	analysis.dependencies.frameworks = [
		{name: 'React', version: '18.0.0', category: 'web', confidence: 'high'},
		{name: 'Next.js', version: '13.0.0', category: 'web', confidence: 'high'},
	];
	analysis.dependencies.testingFrameworks = ['Jest', 'Cypress'];
	analysis.structure.importantDirectories = ['src', 'components', 'pages'];
	analysis.keyFiles.config = ['package.json', 'tsconfig.json'];
	analysis.keyFiles.documentation = ['README.md'];
	analysis.keyFiles.test = ['app.test.ts'];
	analysis.keyFiles.build = ['webpack.config.js'];
	analysis.buildCommands = {
		Build: 'npm run build',
		Test: 'npm test',
	};
	analysis.structure.scannedFiles = 600;
	analysis.repository = 'https://github.com/test/complex-app';

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	// Verify all major sections are present
	t.true(result.includes('# AGENTS.md'));
	t.true(result.includes('ComplexApp'));
	t.true(result.includes('A complex full-stack application'));
	t.true(result.includes('## Project Overview'));
	t.true(result.includes('## Architecture'));
	t.true(result.includes('## Key Files'));
	t.true(result.includes('## Development Commands'));
	t.true(result.includes('## Code Style Guidelines'));
	t.true(result.includes('## Testing'));
	t.true(result.includes('## AI Coding Assistance Notes'));
	t.true(result.includes('## Repository'));
	t.true(result.includes('Large codebase'));
});

test('generateAgentsMd handles nested directory paths', t => {
	const analysis = createMinimalAnalysis();
	analysis.structure.importantDirectories = [
		'src/components',
		'src/utils',
		'nested/deep/components',
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	// Should extract last part of path for description
	t.true(result.includes('- `src/components/` - React/UI components'));
	t.true(result.includes('- `src/utils/` - Utility functions'));
	t.true(result.includes('- `nested/deep/components/` - React/UI components'));
});

test('generateAgentsMd handles file paths with different cases', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.config = [
		'Package.json',
		'TSCONFIG.JSON',
		'webpack.CONFIG.js',
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	// File description matching should be case-insensitive
	t.true(result.includes('- `Package.json` - Node.js dependencies and scripts'));
	t.true(result.includes('- `TSCONFIG.JSON` - TypeScript configuration'));
	t.true(
		result.includes('- `webpack.CONFIG.js` - Webpack build configuration'),
	);
});

test('generateAgentsMd includes Dockerfile and Makefile descriptions', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.config = ['Dockerfile', 'docker-compose.yml', 'Makefile'];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- `Dockerfile` - Docker configuration'));
	t.true(result.includes('- `Makefile` - Build automation'));
});

test('generateAgentsMd handles rollup configuration files', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.config = ['rollup.config.js'];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- `rollup.config.js` - Rollup build configuration'));
});

test('generateAgentsMd handles unknown config files', t => {
	const analysis = createMinimalAnalysis();
	analysis.keyFiles.config = ['custom.config.js', 'unknown.yml'];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	t.true(result.includes('- `custom.config.js` - Configuration file'));
	t.true(result.includes('- `unknown.yml` - Configuration file'));
});

test('generateAgentsMd does not include framework notes for unknown frameworks', t => {
	const analysis = createMinimalAnalysis();
	analysis.dependencies.frameworks = [
		{name: 'UnknownFramework', category: 'other', confidence: 'low'},
	];

	const result = AgentsTemplateGenerator.generateAgentsMd(analysis);

	// Should include the framework in the list but no specific notes
	t.true(result.includes('- UnknownFramework - other'));
	// Should not have any specific framework-related guidance beyond general notes
	t.true(result.includes('## AI Coding Assistance Notes'));
});
